services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      host: db
      port: 5432
      database: ${POSTGRES_DB:-incidencias_db}
      user: ${POSTGRES_USER:-root}
      password: ${POSTGRES_PASSWORD:-rootpassword}
      PORT: 3000
    depends_on:
      - db
    networks:
      - incidencias-net

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - incidencias-net

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-incidencias_db}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rootpassword}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-seed:/docker-entrypoint-initdb.d
    networks:
      - incidencias-net

  pgweb:
    image: sosedoff/pgweb:latest
    restart: on-failure
    depends_on:
      - db
    environment:
      PGWEB_DATABASE_URL: postgres://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-rootpassword}@db:5432/${POSTGRES_DB:-incidencias_db}?sslmode=disable
    ports:
      - "8081:8081"
    networks:
      - incidencias-net

networks:
  incidencias-net:

volumes:
  pgdata:
